### ISSUE TITLE
Bigquery cannot insert

### ISSUE THREAD

**Issue by riderx** [supabase/wrappers#124]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

After follow this tutorial: 
https://supabase.com/docs/guides/database/extensions/wrappers/bigquery#basic-example

I can query the table people without issue.

If I try to insert as it say in the doc, it's possible.

I get this error: 
### Failed to run SQL query: option 'rowid_column' is required
```sql
insert into people(id,name,ts) values (4, 'test name', current_timestamp);
```

## To Reproduce

Follow the BigQuery tutorial in Supabase doc, then try to do the insert i shared.

## Expected behavior

Insert should work as shared in the doc

## Screenshots

![CleanShot 2023-08-04 at 06 38 09@2x](https://github.com/supabase/wrappers/assets/4084527/976e2f6d-7816-4a82-a0a4-68de33b3b200)

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by riderx** [comment]
it seems if i create the table like that:
```sql
-- create foreign table people (
--   id bigint,
--   name text,
--   ts timestamp
-- )
--   server bigquery_server
--   options (
--     table 'people',
--     rowid_column 'id',
--     location 'EU'
--   );
```
it's okay

**Comment by riderx** [comment]
even with owner role in sevice account and user it don't change anything :/

**Comment by riderx** [comment]
I received from Rodrigo Martins Mansueli
In the support this to try:

Can we make sure the service account has correct permissions to write to target table first? You can use below commands as an example.

make sure gcloud CLI is installed, ref: https://cloud.google.com/sdk/docs/install
open a command line window and authenticate using the service account
gcloud auth activate-service-account [your-service-account@your-project.iam.gserviceaccount.com](mailto:your-service-account@your-project.iam.gserviceaccount.com) --key-file ~/your-service-account-credential.json
use bq command to run some testing SQL
bq query --use_legacy_sql=false "insert into your_target_table(column) values('test value')"
If all the above commands are okay, that means the service account has correct permissions setup.

What I did and it worked.

I also answered this that reading the table works properly.
And I have only one service account in the whole Google account.

So I don’t believe it’s miss configuration.
In the documentation I don’t see anything sharing about insert, so I had to guess the rowid_column.
And when I look at the code I see the insert test code is commented.

so that why I wasn’t sure the writing code is working as expected.

I believe an insert example could help, I probably miss something obvious

**Comment by burmecia** [comment]
The reason why the insert test code is commented is because BigQuery mock service doesn't support data modify, so we have to exclude it, but we do have internal service using this FDW to write data and it works fine.

For this case I think the cause is incorrect permission for the service account. For a temporary test, can you grant `BigQuery Admin` role to the service account used in the foreign server and try again? This is to make sure connection and credential config is correct, after that we can reduce the permission to minimum.

**Comment by riderx** [comment]
Thanks for the explaination for the code i understand.

I agree the message seems the permission but i don't understand how it could be that.

I already share in my first message the service account was admin, i even try to put it owner.

And i tried the command upper in my shell and i can write with this exact service account.

I also tried to add in my dev db the wrapper and no better luck.

Here is some screens

![CleanShot 2023-08-09 at 12 30 44@2x](https://github.com/supabase/wrappers/assets/4084527/9c3f8b1d-dc81-4310-bb5f-e217aba636d2)
![CleanShot 2023-08-09 at 12 33 02@2x](https://github.com/supabase/wrappers/assets/4084527/fbc8dfd4-f664-4394-8048-d4a926411196)
![CleanShot 2023-08-09 at 12 33 30@2x](https://github.com/supabase/wrappers/assets/4084527/aa5aae45-4d55-4afe-b880-8287e63a0558)

I just tried to delete bigquery and add it again with web interface instead of sql. Same issue.
I can see the table but cannot write.
![CleanShot 2023-08-09 at 12 37 09@2x](https://github.com/supabase/wrappers/assets/4084527/00858079-23d9-48f2-a57d-eb786ad6d429)
![CleanShot 2023-08-09 at 12 37 23@2x](https://github.com/supabase/wrappers/assets/4084527/5524a63a-fb32-443c-b624-242f63f8d07c)

**Comment by riderx** [comment]
By the way now i cannot go to the bigquery wrapper in the web interface:
![CleanShot 2023-08-09 at 13 07 55@2x](https://github.com/supabase/wrappers/assets/4084527/72f7cfc1-fe8c-4eba-bc78-b27b491a569d)
While stripe one doesn't have issue

**Comment by riderx** [comment]
First time i configured it was without vault. now i it's in the vault.
![Uploading CleanShot 2023-08-09 at 13.09.19@2x.png…]()

**Comment by riderx** [comment]
I just gave up and switched to clickhouse who work for insert.
Now my issue is how to configure RLS on foreign table, postgres refuse to add RLS even with a view.
So right now i cannot use foreign for some frontend users query

**Comment by burmecia** [comment]
I think this issue is caused by upstream GCP client lib change, will raise a PR to fix it soon.

**Comment by burmecia** [comment]
RLS cannot work with foreign table, I'd suggest to sync it up with a mirror table and then enable RLS on it. To keep the mirror table in sync, you can use `pg_cron` or other external tools to schedule a repeating job to copy data from foreign table to the mirror table.

**Comment by riderx** [comment]
The point of having wrapper table on ClickHouse or BigQuery for Capgo is to store the data in a db who handle the load and query for timeseries.
Mirroring the table of + 1M row, have no interest then, i have already the data in the db now, it just bloat my db usage.
