### ISSUE TITLE
Personal Access Tokens don't work with the Airtable Wrapper

### ISSUE THREAD

**Issue by jpedroschmitz** [supabase/wrappers#159]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

API keys will be [deprecated](https://support.airtable.com/docs/airtable-api-key-deprecation-notice) by the end of January 2024 on Airtable. After this date, API keys will stop working and we'll have to migrate to personal access tokens. Personal access tokens allow you to more securely grant API access to Airtable data.

Personal access tokens should be passed with your API requests as a `Authorization: Bearer header`.

```sh
curl https://api.airtable.com/v0/YOUR_BASE_ID/YOUR_TABLE_ID_OR_NAME -H \
"Authorization: Bearer YOUR_TOKEN"
```

I looked into the source code of the `airtable_fdw` and it looks like we're already authenticating using `Authorization: Bearer header`, but when I tried creating a personal access token to use with the wrapper, I get the following error:

```
Error running SQL: Failed to run sql query: invalid secret id "<TOKEN>": failed to parse a UUID
```

This is an example (won't work) of a token:

```
patbYo3eCBwtOuRLL.db934f8b0634c9f2f5471458b55222fb1231d1a3600bd09ww87f8c760b475b74
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Follow the steps to create the Airtable integration (https://supabase.com/docs/guides/database/extensions/wrappers/airtable)
2. Instead of using the API Key, use a Personal Access Token (https://airtable.com/create/tokens)
3. Run your select query and see the error

## Expected behavior

The Airtable wrapper should work with Personal Access tokens.

## Screenshots

N/A

## System information

N/A

## Additional context

N/A

**Comment by imor** [comment]
@jpedroschmitz how did you set the PAT? Did you save it in the vault or use it without the vault? The error could occur if the PAT was set in the `api_key_id` option. If you don't want to use the vault, try setting the PAT in the `api_key` option:

```sql
create server airtable_server
  foreign data wrapper airtable_wrapper
  options (
    api_key 'patbYo3eCBwtOuRLL.db934f8b0634c9f2f5471458b55222fb1231d1a3600bd09ww87f8c760b475b74'
  );
```

Alternatively, if you do want to use the vault, first save the PAT in the vault:

```sql
-- Save your Airtable PAT in Vault and retrieve the `key_id`
insert into vault.secrets (name, secret)
values (
  'AirtablePAT',
  'patbYo3eCBwtOuRLL.db934f8b0634c9f2f5471458b55222fb1231d1a3600bd09ww87f8c760b475b74'
)
returning key_id;
```

This should print a `key_id`.

Next, set the `key_id` in the `api_key_id` option:

```sql
create server airtable_server
  foreign data wrapper airtable_wrapper
  options (
    api_key_id '<key_id>' -- The key_id from when the PAT was saved in the vault.
  );
```

This is documented here: https://supabase.github.io/wrappers/airtable/

**Comment by jpedroschmitz** [comment]
It worked now! Thanks for the quick reply

**Comment by imor** [comment]
Thanks @jpedroschmitz for confirming that it works. We're updating [the docs](https://github.com/supabase/wrappers/pull/161) to make it clear how to set the PAT.
