### ISSUE TITLE
Use of GitHub-specific emoji syntax breaks documentation in other contexts

### ISSUE THREAD

**Issue by brandondrew** [supabase/wrappers#211]
# Improve documentation

## Link 

https://pgt.dev/extensions/wrappers

## Describe the problem

If you take a look at the README as it appears  on [the Trunk web site](https://pgt.dev/extensions/wrappers), you'll notice that instead of emojis ✅ and ❌, you see `:white_check_mark:` and `:x:` in the columns.

## Describe the improvement

Instead of using GitHub-specific syntax, just use emojis.  

## Additional context

Emojis are part of unicode, and are far more widely supported than GitHub's alternative emoji codes.

**Comment by imor** [comment]
@brandondrew thanks for reporting. This will be fixed in #212
