### ISSUE TITLE
Add Stripe API URL configuration and documentation

### ISSUE THREAD

**Issue by kyeshmz** [supabase/wrappers#219]
# Improve documentation

## Link 

https://supabase.github.io/wrappers/stripe/#connecting-to-stripe

## Describe the problem

Its missing, and confusing. Is there a reason why `https://api.stripe.com`  is not inserted by default?

## Describe the improvement

add that `https://api.stripe.com` is the default base URL.
Documented here`https://stripe.com/docs/api`

Without this, all DB operations fail, so making it undefined if it is not valid seems off.

## Additional context
![Uploading Screenshot 2024-01-05 at 4.48.29 PM.png…]()

**Comment by imor** [comment]
Did you run into an issue while configuring stripe fdw? What was the exact error and what was missing from the docs that caused you to run into it? There's no config for stripe_fdw that needs the base_url `https://api.stripe.com` so I'm a little confused. Also looks like the attached png link is broken.

**Comment by kyeshmz** [comment]
Yes, going through the initial documentation using SQL queries didn't resolve the API URL so everything returned undefined.
But it seems now that it is fixed and returns api/v1 on default.

<img width="984" alt="Screenshot 2024-01-09 at 8 34 43 AM" src="https://github.com/supabase/wrappers/assets/12763472/dc2aefe9-fab4-4e78-9d0f-2560321b1190">

**Comment by kyeshmz** [comment]
I think there still should be documentation explaining this, or maybe fix this to use a select modal of v1 or v2 when its necessary? 
I have only really used stripe as a personal account, so I do not know if there are edge cases for enterprises when the API URL would be different.

**Comment by imor** [comment]
Thanks @kyeshmz, @burmecia has opened [a PR](https://github.com/supabase/wrappers/pull/221) to mention `api_url` in the docs.
