### ISSUE TITLE
Publish v0.2 on crates.io

### ISSUE THREAD

**Issue by Jayko001** [supabase/wrappers#227]
Hey, I am currently developing https://github.com/tembo-io/prometheus_fdw and https://github.com/tembo-io/clerk_fdw using Supabase Wrappers. I would like to include the latest features in these FDW's.

Thank you.

**Comment by imor** [comment]
@Jayko001 we have published version `supabase-wrappers` version `0.1.16` which contains the latest changes. Note that the docs.rs build failed which we will fix soon. If you need to read docs meanwhile you can build the docs locally if needed.

**Comment by imor** [comment]
Closing this issue as `supabase-wrappers` version `0.1.17` is available on both crates.io and docs.rs.
