### ISSUE TITLE
Cant find Clerk FDW inside extension list

### ISSUE THREAD

**Issue by firmableharry** [supabase/wrappers#232]
# Bug report

- [ ] I confirm this is a bug with Supabase, not with my own application. 
- [ ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Can't find Clerk FDW inside the extension list

## To Reproduce

As per this blog post - https://supabase.com/blog/supabase-wrappers-v02 under "New Wrappers and Improvements", it is mentioned as Clerk as supported FDW.

## Expected behavior

However, I cant find inside the Supabase instance, (updated to latest pg version as well)

![image](https://github.com/supabase/wrappers/assets/121205240/39e2782c-3fa5-4030-8d9d-a0b3ede672f2)

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

## Additional context

Paul and Tembo team agreed that it will be supported as long as Tembo maintains this (on X)

**Comment by WesleyYue** [comment]
From the article
> We cannot support community Wrappers inside the Supabase Dashboard until the Wrappers API is stabilized. You can vote your favorite Wrapper if you'd like it to be added to Supabase in the future. If you have developed a Wrapper that you want inside the Supabase Dashboard, please contribute it as a PR in [the wrappers repo](https://github.com/supabase/wrappers). Once we release Wrappers 1.0, we will support community Wrappers within the Supabase Dashboard.

**Comment by imor** [comment]
`clerk_fdw` is not currently available as mentioned in the blog post.
