### ISSUE TITLE
Clickhouse FDW w/ View and Vault Error

### ISSUE THREAD

**Issue by ryan-managai** [supabase/wrappers#246]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Using Clickhouse private schema w/ a public view that exposes some data doesn't work when using Vault `conn_string_id`.

I was able to get clickhouse working w/ a FDW that stores everything in a private schema table. It exposes a public view. When switching to vault, and attempting to access my view, I get the error:

`permission denied for schema vault`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Setup a new private schema (I called it clickhouse).
2. Follow all steps outlined in clickhouse docs (using Vault)
3. Create a foreign table in a private instead of public schema (i.e. `create foreign table clickhouse.my_priv_table ...`)
4. Create a public view from that table: `CREATE VIEW my_public_table my WITH (security_invoker) AS SELECT * FROM clickhouse.my_priv_table;`
5. Attempt to access the public view w/ an authenticated user.

## Expected behavior

I should be able to access the public view when using vault to store connection details.

## Screenshots
![Screenshot 2024-03-22 at 5 01 32 PM](https://github.com/supabase/wrappers/assets/152729119/10f1e957-2a28-4371-a7c1-48dd65b5a00f)

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by burmecia** [comment]
When the view is created with `WITH (security_invoker)`, access to the underlying foreign table is determined by the permissions of the user executing the query, not the view owner. So you need to make sure the user who is using the view to have permission on `vault` schema because it needs read encrypted secrets from `vault` schema.

To grant that permission, you can try below sqls:

```sql
GRANT USAGE ON SCHEMA vault TO <relevant role>;
GRANT SELECT ON TABLE vault.decrypted_secrets TO <relevant role>;
```

**Comment by ryan-managai** [comment]
Hmm, still getting the same error. Trying to access via authenticated user, and simulating via Supabase's role settings right now. 

Am I correct in that `GRANT USAGE`/`GRANT SELECT` would be limited to server-side, not client, given how supabase doesn't allow access to tables outside public? I wouldn't want decrypted_secrets exposed to allow any authenticated user to grab them.

Is there any alternative to storing the creds directly in postgres when using FDW's?

**Comment by burmecia** [comment]
When you're impersonating an authenticated user in Supabase UI, can you make sure that user really has `authenticated` role?

**Comment by ryan-managai** [comment]
Getting the same error both in the Supabase dashboard, and via a logged in authenticated user (despite running migrations). 

I was able to create a new schema via the dashboard called `test`, and grant the aforementioned permissions and then access it via an authenticated user. I am not able to do the same with vault.

```
CREATE SCHEMA test;

...

GRANT USAGE ON SCHEMA test TO authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA test TO authenticated;
```

Works fine

```
GRANT USAGE ON SCHEMA vault TO authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA vault TO authenticated;
```

Does not work.

**Comment by burmecia** [comment]
The problem is probably because `GRANT USAGE ON SCHEMA vault TO authenticated;` didn't take effects but that warning message doesn't shown on Supabase dashboard. If you're using psql with `postgres` user, you will see the warning message `WARNING:  no privileges were granted for "vault"` when you run `GRANT USAGE on SCHEMA vault`.

So the thing is there are some extra permissions needed for custom users, for you case it might be better to raise a support ticket and we can help you sort it out.

**Comment by ryan-managai** [comment]
@burmecia I closed this, and will open a support ticket. 

However, thinking this through, Supabase recommends the following:
1. Store things like connection details in Vault
2. Don't expose most wrappers via the public schema. Instead, put them in a private schema and expose them via a view or function.

Having said that, should the examples be updated to include anything necessary to get both of those working simultaneously? I'm just trying to follow the provided best practices, and I'm surprised others aren't hitting this as well.

**Comment by burmecia** [comment]
Yes, to grant the `vault` schema permission we need go through support as the `supabase_admin` role is managed by Supabase. We definitely need improvements on the docs to provide more on the best practices, it is already on our task list and thank you for your feedback.

**Comment by aplyd** [comment]
> It looks like Vault is owned by `supabase_admin`, which if I understand correctly, we don't have access to. So, we need to go through support? But, this repo recommends using Vault. Maybe I'm missing something.

I'm also confused because the docs led me to a dead end. I created a public view to access my private stripe schema but now can't actually query the view from the client because the user needs access to the vault. Should I just resort to using a function instead?

**Comment by burmecia** [comment]
The vault schema contains sensitive data so it should be protected carefully. As the [docs suggested](https://supabase.com/docs/guides/database/extensions/wrappers/overview#security), using `security definer` function to access foreign table is the best practice as it simplified the complex permissions grants. Note that `security definer` function must be defined by `postgres` user (you can do it in SQL Editor) so the other roles/users can access it.
