### ISSUE TITLE
`limit` is alwasy `None`

### ISSUE THREAD

**Issue by samuelcolvin** [supabase/wrappers#253]
# Bug report

I've tried adding `limit 1` etc. to a query, but the `limit: &Option<Limit>` parameter to `begin_scan` seems to always be `None`.

I tried setting `offset 1 limit 1` since `Limit` seems to be always contain both `limit` and `offset`, but it didn't help.

---

I'm building on MacOS with `cargo pgrx run pg15`, using `pgrx = { version = "=0.11.2" }` and `cargo --version cargo 1.77.1 (e52e36006 2024-03-26)`, using `superbase-wrappers` `main` as per #252

**Comment by burmecia** [comment]
I suppose this has been fixed in the latest version of Wrappers, as it cannot be reproduced anymore. Feel free to open a new ticket with more details if that happened again.
