### ISSUE TITLE
The products table is empty if the stripe account API version is old

### ISSUE THREAD

**Issue by vickkhera** [supabase/wrappers#291]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

My stripe account is very old, and had the "default API version 2016-03-07" set in the developer console. I have three products defined via the Stripe dashboard but none of them showed up in the wrapped tables in Supabase on `select * from stripe.products`. If I created a product by inserting into the table, I could see it on select but none other. The newly created product also shows up on the Stripe dashboard list of products. In Postgres running the query in the `psql` CLI, no warnings or errors are shown, just an empty list.

To debug this, I did a bunch of Stripe API calls via `curl` on my command line, and one of the tests returned this error to me:

```
curl -G https://api.stripe.com/v1/products/search -u "sk_test_XXXX:" --data-urlencode query="active:'true'"
{
  "error": {
    "message": "Search is not supported on api version 2016-03-07. Update your API version, or set the API Version of this request to 2020-08-27 or greater.",
    "request_log_url": "https://dashboard.stripe.com/logs/req_4bPEPEO1nvuTtj?t=1718974843",
    "type": "invalid_request_error"
  }
}
```

Upgrading my Stripe account's API version (bottom of the screen at https://dashboard.stripe.com/developers) to the latest, 2024-04-10, resolved this error. Now queries from the wrapper in supabase return all my products.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to Stripe and set the API version to an old one (not even sure this is possible)
2. Run the query in supabase `select * from stripe.products`
3. empty list is returned

## Expected behavior

The query should always return a list, or show the stripe API error.

The wrapper should explicitly request the latest API by setting the `Stripe-Version` header as per https://docs.stripe.com/api/versioning since it depends on the search endpoint which is not available until the 2020-08-27 version.

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by vickkhera** [comment]
You can recreate the error by specifying the version in the `curl` command:

```
curl -G https://api.stripe.com/v1/products/search -u "sk_test_XXXX:" -H "Stripe-Version: 2016-03-07" --data-urlencode query="active:'true'"
```

**Comment by burmecia** [comment]
Thank you for reporting this issue. We're using `/products` instead of `/products/search` endpoint to retrieve product list, and Stripe returns an empty list without any errors:

```bash
curl -G https://api.stripe.com/v1/products \
  -u "sk_test_xxx:" \
  -H "Stripe-Version: 2016-03-07" \
  -d limit=3
```

The response is:

```json
{
  "object": "list",
  "data": [],
  "has_more": false,
  "url": "/v1/products"
}
```

Wrappers cannot distinguish this response with an invalid API version error, so we probably cannot fix this issue.

**Comment by vickkhera** [comment]
The problem is that it is returning an empty list instead of the actual list. If you run that with the current stripe version, it gives you the full list.

```sh
% curl -G https://api.stripe.com/v1/products -u "sk_test_XXX:" -H "Stripe-Version: 2016-03-07"
{
  "object": "list",
  "data": [],
  "has_more": false,
  "url": "/v1/products"
}%
```

vs with the current API version:

```sh
% curl -G https://api.stripe.com/v1/products -u "sk_test_XXX:" -H "Stripe-Version: 2020-08-27"
{
  "object": "list",
  "data": [
    {
      "id": "prod_QKWuHzeDfpzD7J",
      "object": "product",
      "active": true,
      "attributes": [],
      "created": 1718916289,
...
```

**Comment by vickkhera** [comment]
If you're not going to explicitly request a modern stripe API version in your API calls (which is a reasonable fix for this problem), then please at least tell the users that if their API version configured at their Stripe developer dashboard is older than `2020-08-27` this extension will not return any product data to them.

**Comment by burmecia** [comment]
thanks for the suggestion, we will improve it in the docs.
