### ISSUE TITLE
Timestamp with timezone not supported

### ISSUE THREAD

**Issue by paul-brenner** [supabase/wrappers#292]
I see that it was added in a [new commit last month](https://github.com/supabase/wrappers/commit/d2ca6ae08fa0da66fb77b5619f1c6e83321a0b78#diff-a4d9e5ca40867b444fab85d92fbbec6d056f2fbb4727b257e9b5631c9953aba0), but there hasn't been a new release. 

Is there somewhere better for me to express my encouragement for this to be released in a new version?

**Comment by burmecia** [comment]
we're preparing for a new release and it should be ready soon, thank you for your attention.

**Comment by paul-brenner** [comment]
Thank you!
