### ISSUE TITLE
Documentation: Wasm Foreign Data Wrapper 

### ISSUE THREAD

**Issue by aluferraz** [supabase/wrappers#305]
# Improve documentation

## Describe the problem

I see WASM fdw source code but I can't find any documentation describing it.

## Describe the improvement

Documentation/examples of the WASM FDW.\

**Comment by burmecia** [comment]
The WASM wrappers were just added recently, docs are still in progress and will be released soon. Thanks for your attention!

**Comment by burmecia** [comment]
The WASM FDW docs have been updated https://supabase.github.io/wrappers/.

An example WASM FDW has also been created, check it out at https://github.com/supabase-community/wasm-fdw-example

**Comment by aluferraz** [comment]
Thanks a lot!!
