### ISSUE TITLE
Critical Issue: Stripe Wrapper Data Not Displaying on Supabase

### ISSUE THREAD

**Issue by br0wsa** [supabase/wrappers#376]
# Stripe Wrapper Data Not Displaying on Supabase

## Description
I am experiencing an issue with the Stripe wrapper in my Supabase database. The data from the wrapper is not displaying, including for all associated foreign tables.

## Details
- **Database:** Supabase
- **Infrastructure:** AWS | eu-west-1

### Issues encountered:
- Unable to delete the wrapper.
- Unable to add or remove tables from this wrapper.
- There seems to be a timeout with the API Gateway.

## Questions
Is anyone else experiencing the same issue?

Thank you in advance for your help!

**Comment by br0wsa** [comment]
- I confirm this is a bug with Supabase, not with my own application.
- I confirm I have searched the [Docs](https://docs.supabase.com/), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [X](https://x.com/supabase).

##  System information

- OS : Ubuntu last version
- Browser :  _if applies_ Chrome

## Details
- **Database:** Supabase
- **Infrastructure:** AWS | eu-west-1

### Steps Taken
1. Created a Stripe account (_test_).
2. Created a view with a `WITH` query that references the foreign table (in my case, Stripe Checkout Session).
3. Executed a simple `SELECT` on the view.

### Issues Encountered:
- No data in the view.
- No data in any Stripe foreign table.
- Impossible to delete the wrapper.
- Impossible to modify, add, or delete a Stripe table.
- There seems to be a timeout with the API Gateway.

**Comment by burmecia** [comment]
Thanks for reporting this issue. I've tried to troubleshoot the issue on Supabase but cannot reproduce it. Can you provide more details, such as Postgres version, Wrappers version or any error messages? I saw you're using foreign table in a view, can you directly run a `SELECT` query on the foreign table to see if any results?

**Comment by br0wsa** [comment]
> Thanks for reporting this issue. I've tried to troubleshoot the issue on Supabase but cannot reproduce it. Can you provide more details, such as Postgres version, Wrappers version or any error messages? I saw you're using foreign table in a view, can you directly run a `SELECT` query on the foreign table to see if any results?

after all the steps I simply restarted my database and that resolved the malfunction. I am unable to say what caused this blockage. I emphasize that I was in 100% test mode with stripe and that now with a second wrapper I am in real payment. Thank you for your kind help.

**Comment by burmecia** [comment]
you're welcome, glad to see the issue has been resolved.
