### ISSUE TITLE
feat: create a FDW can read file data from S3

### ISSUE THREAD

**Issue by burmecia** [supabase/wrappers#61]
# Feature request

## Describe the feature

Create a FDW can read file data from S3, it will also be compatible with Supabase Storage. 

## Additional context

- Read-only should be enough for the first stage, we can implement writing in the next release.
- If we can support multiple sequence files read and common compressions like gzip, that will be great.

**Comment by elvise** [comment]
@burmecia we can close this issue as I can see the fdw as released, is it correct ?

**Comment by burmecia** [comment]
> @burmecia we can close this issue as I can see the fdw as released, is it correct ?

yes, the initial version of S3 FDW is ready now, it supports read only and common compressions. Although data write, Supabase Storage and multiple sequence files are not supported yet, we can put it in future enhancement. Let's close this first.
