### ISSUE TITLE
BigQuery wrapper: JSON, Numeric not supported

### ISSUE THREAD

**Issue by yan-hic** [supabase/wrappers#70]
Trying to query a table with JSON data type in BigQuery.

Foreign table, with `json` column type, gets created fine but upon querying, the wrapper returns:
```
Failed to run sql query: get table metadata failed: Request error (error: error decoding response body: unknown variant `JSON`, expected one of `STRING`, `BYTES`, `INTEGER`, `INT64`, `FLOAT`, `FLOAT64`, `NUMERIC`, `BIGNUMERIC`, `BOOLEAN`, `BOOL`, `TIMESTAMP`, `DATE`, `TIME`, `DATETIME`, `RECORD`, `STRUCT` at line 15 column 22)
```

**Comment by yan-hic** [comment]
The workaround I used till supported: 

1. use `json_to_string()` in bigquery
2. in the foreign table ddl, define that column as `text` and add a generated column to convert back to json (`jsonStringColumn::json`)

**Comment by burmecia** [comment]
Yes, JSON is not support yet in BigQuery FDW. A workaround is using `TO_JSON_STRING` to convert JSON to STRING in BigQuery and store that string as source table column. Then use subquery or view on top of PG foreign table and convert that string back to JSON.

**Comment by burmecia** [comment]
We're currently working on improving BigQuery fdw, the JSON support should be ready on the next release. And thanks for the subquery in `table` option, it is quite useful, we will evaluate and hopefully include it in the future release.

**Comment by yan-hic** [comment]
EDIT: I have edited the title and added `Numeric`:
`Failed to run sql query: field type Numeric not supported`

which is a valid type in PG: https://www.postgresql.org/docs/current/datatype-numeric.html

Would be good to add all supported ones or document the limited support.
Thanks.

**Comment by rubenvereecken** [comment]
@burmecia I believe this should be reopened. #78 added numeric support, but not JSON, which was the main issue raised originally.

**Comment by jscheel** [comment]
@burmecia what happened to the json support?

**Comment by burmecia** [comment]
@jscheel, it has JSON writing support for now, but not for reading. We will be adding it soon.

**Comment by jscheel** [comment]
@burmecia awesome! Thank you!
