### ISSUE TITLE
BigQuery wrapper: generated column error

### ISSUE THREAD

**Issue by yan-hic** [supabase/wrappers#71]
As a workaround for the wrapper not supporting JSON column type, we wanted to use a generated column to cast to json on-the-fly.

The idea was to add a column like `jsonCol json GENERATED ALWAYS AS (cast(jsonStringCol as json)) STORED`. 
However that fails and I suspect the wrapper tries to map it with a source column instead of computing it.

### To reproduce:
Using the steps at https://github.com/supabase/wrappers/tree/main/wrappers/src/fdw/bigquery_fdw, edit the foreign table ddl like so:
```
create foreign table people (
  id bigint,
  name text, 
  ts timestamp,
  test text generated always as (substring(name, 3, 2)) stored
)
  server bq_tmp
  options (
    table 'people',     -- source table in BigQuery, required
  );

select * from people
```

### Error
```
Failed to run sql query: get table metadata failed: Response error (error: ResponseError { error: NestedResponseError { 
code: 400, errors: [{"reason": "invalid", "message": "Selected non-existent field: test", "domain": "global"}], 
message: "Selected non-existent field: test", status: "INVALID_ARGUMENT" } })
```

### Workaround
Suboptimal, create/use a view

**Comment by burmecia** [comment]
thank you for the reporting this issue! The generated column is not supported yet, but should not report error if it is used. We will raise a fix for this soon.

**Comment by yan-hic** [comment]
@burmecia not sure I understand - what is not supported: generated columns on write and/or on read ? On reading, it should fall back on standard PostGres feature - which is probably what the PR is about.
Please elaborate on what is not supported yet. Thanks

**Comment by burmecia** [comment]
Postgres currently implements only stored (on write) generated columns, virtual (on read) generated columns are not supported by Postgres. Wrappers doesn't support the stored generated columns, but it should not report an error when using it.
