### ISSUE TITLE
Replace references to PGX with references to PGRX

### ISSUE THREAD

**Issue by dventimihasura** [supabase/wrappers#86]
# Improve documentation

## Link 

https://github.com/supabase/wrappers

## Describe the problem

The documentation refers to PGX, but evidently PGX is now PGRX.  Perhaps its name changed, but in any case, this changes the installation instructions and leads to confusion.

## Describe the improvement

Change all references to PGX, to PGRX.  For instance:

1. Built on top of pgx, providing higher level interfaces, without hiding lower-level C APIs. -> Built on top of pgrx, providing higher level interfaces, without hiding lower-level C APIs.
2. Wrappers is a pgx extension, you can follow the pgx installation steps to install Wrappers. -> Wrappers is a pgrx extension, you can follow the pgrx installation steps to install Wrappers.
3. cargo pgx install --pg-config [path_to_pg_config] --features stripe_fdw -> cargo pgrx install --pg-config [path_to_pg_config] --features stripe_fdw
4. Run it using pgx with feature -> Run it using pgrx with feature
5. cargo pgrx run pg14 --features helloworld_fdw
6. cargo pgx test --features all_fdws,pg15 -> cargo pgrx test --features all_fdws,pg15
7. Windows is not supported, that limitation inherits from pgrx -> Windows is not supported, that limitation inherits from pgrx

**Comment by dventimihasura** [comment]
Nevermind.  Maybe it's just enough to point out that pgx became pgrx between 0.7.4 and 0.8.0, that it introduced breaking changes when it did so, and that therefore for Supabase wrappers you should not follow the exact instructions on the pg(r)x site and instead install pgx.  I.e.,

Instead of 

```shell
cargo install --locked cargo-pgrx
```

do

```shell
cargo install --locked cargo-pgx
```

**Comment by dventimihasura** [comment]
Addendum. Evidently, wrappers requires pgx 0.6.1, not 0.7.4:

```shell
cargo install --locked --version=0.6.1 cargo-pgx
```

**Comment by burmecia** [comment]
Thanks @dventimihasura , you're right, the wrappers can only support pgx 0.6.1, and we're in the progress to catch up with pgx's latest changes.
